"""added specimen to ClinicalData

Revision ID: 4f2c8bef2c88
Revises: e9659b7e3f83
Create Date: 2025-07-10 20:55:32.153332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2c8bef2c88'
down_revision: Union[str, Sequence[str], None] = 'e9659b7e3f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
