"""added specimen to ClinicalData

Revision ID: e9659b7e3f83
Revises: 6309e9d8ea5f
Create Date: 2025-07-10 20:52:08.199823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9659b7e3f83'
down_revision: Union[str, Sequence[str], None] = '6309e9d8ea5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clinical_data', sa.Column('specimen', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clinical_data', 'specimen')
    # ### end Alembic commands ###
